<?php
require_once "../includes/auth.php"; require_login("admin"); require_once "../config/db.php";
$msg="";
if(isset($_POST["save_attendance"])){ $sid=(int)$_POST["student_id"];$cid=(int)$_POST["course_id"];$date=$_POST["date"];$status=$_POST["status"]; $stmt=$conn->prepare("INSERT INTO attendance(student_id,course_id,attendance_date,status) VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE status=VALUES(status)");$stmt->bind_param("iiss",$sid,$cid,$date,$status);$stmt->execute();$msg="Attendance saved."; }
$students=$conn->query("SELECT id,full_name,student_id FROM users WHERE role='student' ORDER BY full_name");$courses=$conn->query("SELECT id,course_code FROM courses ORDER BY course_code");$rows=$conn->query("SELECT a.*,u.full_name,c.course_code FROM attendance a JOIN users u ON a.student_id=u.id JOIN courses c ON a.course_id=c.id ORDER BY a.attendance_date DESC LIMIT 30");
$page_title="Attendance";$css_path="../assets/css/style.css";$js_path="../assets/js/main.js";require "../includes/header.php";
?>
<div class="dashboard"><aside class="sidebar"><?php include "sidebar.php"; ?></aside><main class="dash-main"><h1>Attendance Management</h1><?php if($msg):?><div class="alert success"><?=e($msg)?></div><?php endif;?>
<div class="panel"><h2>Record Attendance</h2><form method="POST" class="form-grid"><select name="student_id" required><option value="">Student</option><?php while($s=$students->fetch_assoc()):?><option value="<?=$s["id"]?>"><?=e($s["student_id"]." - ".$s["full_name"])?></option><?php endwhile;?></select><select name="course_id" required><option value="">Course</option><?php while($c=$courses->fetch_assoc()):?><option value="<?=$c["id"]?>"><?=e($c["course_code"])?></option><?php endwhile;?></select><input type="date" name="date" value="<?=date('Y-m-d')?>" required><select name="status"><option>Present</option><option>Absent</option><option>Late</option></select><button name="save_attendance" class="btn btn-primary">Save Attendance</button></form></div>
<div class="panel"><h2>Recent Attendance</h2><div class="table-wrap"><table><tr><th>Date</th><th>Student</th><th>Course</th><th>Status</th></tr><?php while($r=$rows->fetch_assoc()):?><tr><td><?=e($r["attendance_date"])?></td><td><?=e($r["full_name"])?></td><td><?=e($r["course_code"])?></td><td><span class="badge"><?=e($r["status"])?></span></td></tr><?php endwhile;?></table></div></div></main></div><?php require "../includes/footer.php"; ?>