<?php
require_once "../includes/auth.php"; require_login("admin"); require_once "../config/db.php";
$msg="";
if(isset($_POST["add_course"])){ $code=trim($_POST["code"]);$name=trim($_POST["name"]);$credit=(float)$_POST["credit"];$dept=(int)$_POST["department_id"];$fid=(int)$_POST["faculty_id"]; $stmt=$conn->prepare("INSERT INTO courses(course_code,course_name,credit,department_id,faculty_id) VALUES(?,?,?,?,?)");$stmt->bind_param("ssdii",$code,$name,$credit,$dept,$fid);$msg=$stmt->execute()?"Course added successfully.":"Could not add course. Course code may already exist."; }
$deps=$conn->query("SELECT * FROM departments ORDER BY name");$fac=$conn->query("SELECT id,full_name FROM users WHERE role='faculty' ORDER BY full_name");$rows=$conn->query("SELECT c.*,d.name department,u.full_name faculty FROM courses c LEFT JOIN departments d ON c.department_id=d.id LEFT JOIN users u ON c.faculty_id=u.id ORDER BY c.id DESC");
$page_title="Courses";$css_path="../assets/css/style.css";$js_path="../assets/js/main.js";require "../includes/header.php";
?>
<div class="dashboard"><aside class="sidebar"><?php include "sidebar.php"; ?></aside><main class="dash-main"><h1>Course Management</h1><?php if($msg):?><div class="alert success"><?=e($msg)?></div><?php endif;?>
<div class="panel"><h2>Add Course</h2><form method="POST" class="form-grid"><input name="code" placeholder="CSE305" required><input name="name" placeholder="Course name" required><input type="number" step=".5" name="credit" placeholder="Credit" required><select name="department_id" required><option value="">Department</option><?php while($d=$deps->fetch_assoc()):?><option value="<?=$d["id"]?>"><?=e($d["name"])?></option><?php endwhile;?></select><select name="faculty_id"><option value="0">Assign faculty</option><?php while($f=$fac->fetch_assoc()):?><option value="<?=$f["id"]?>"><?=e($f["full_name"])?></option><?php endwhile;?></select><button name="add_course" class="btn btn-primary">Add Course</button></form></div>
<div class="panel"><h2>Course List</h2><div class="table-wrap"><table><tr><th>Code</th><th>Course</th><th>Credit</th><th>Department</th><th>Faculty</th></tr><?php while($r=$rows->fetch_assoc()):?><tr><td><?=e($r["course_code"])?></td><td><?=e($r["course_name"])?></td><td><?=$r["credit"]?></td><td><?=e($r["department"]??"—")?></td><td><?=e($r["faculty"]??"Not assigned")?></td></tr><?php endwhile;?></table></div></div></main></div><?php require "../includes/footer.php"; ?>